pipeline {
    agent any
    
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/bohdanius/gcp-cloud-function.git'
            }
        }
        
        stage('Install dependencies') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }
        
        stage('Run tests') {
            steps {
                sh 'pytest tests'
            }
        }
        
        stage('Deploy') {
            steps {
                sh 'gcloud functions deploy dummy-cloud-function --runtime python39 --trigger-http'
            }
        }
    }
    
    post {
       // always {
            // Cleanup steps if necessary
       // }
        success {
            echo 'CI pipeline ran successfully!'
        }
        failure {
            echo 'CI pipeline failed!'
        }
    }
}
